# -------------------------------------------------
# CrowdOrganHost openFrameworks makefile
# -------------------------------------------------

PROJECT_NAME := CrowdOrganHost
PROJECT_ROOT := $(realpath .)

OF_ROOT ?= $(realpath ../../..)

include $(OF_ROOT)/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk
